### PR TITLE
Wazo 3029 - use py39 and bullseye versions

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Review by fblackburn1 — APPROVED** [review]

**Review by fblackburn1 — APPROVED** [review]

**Comment by jfbourque** [comment]
check

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by sopelj** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by fblackburn1** [comment]
Note: status is wrong, the branch has been merged into `bullseye` branch

**Comment by sopelj** [comment]
> Note: status is wrong, the branch has been merged into `bullseye` branch

Yeah, it was really weird. It merged it automatically, but then said it couldn't merge because there were conflicts (But it had merged and that was the conflict). I did a rebase, but there was nothing except the merge. When I pushed the rebase it closed the PR automatically. 🤔

**Pull request closed without merging**
